# Generated by Django 5.0.1 on 2024-05-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0002_alter_blogpost_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image_url',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
