# Generated by Django 5.0.1 on 2024-05-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0004_author_alter_blogpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
