# Generated by Django 5.0.1 on 2024-05-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0006_author_alter_blogpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
