# Generated by Django 5.0.6 on 2024-05-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0007_alter_blogpost_author_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='industry_images/')),
            ],
        ),
    ]
