# Generated by Django 5.0.6 on 2024-05-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0008_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='industry_images/'),
        ),
    ]
