# Generated by Django 5.0.6 on 2024-05-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0012_author_alter_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='website',
            field=models.CharField(default='', max_length=50),
        ),
    ]
